const {
  registerCoach,
  loginCoach,
  getAllSubscriptions,
  createSubscription,
  deleteSubscription,
  updateSubscription,
  createPlan,
  getAllPlans,
  deletePlan,
  updatePlan,
  createWorkout,
  getAllWorkouts,
  deleteWorkout,
  updateWorkout,
  createWorkoutSpecifications,
  getAllWorkoutSpecifications,
  updateWorkoutSpecifications,
  createDiet,
  getDiet,
  updateDiet,
} = require("./userControllers/CoachController");
const {
  registerTrainee,
  loginTrainee,
} = require("./userControllers/TraineeController");
const { login, signup } = require("./authController");

module.exports = {
  registerCoach,
  loginCoach,
  createSubscription,
  getAllSubscriptions,
  deleteSubscription,
  updateSubscription,
  createPlan,
  getAllPlans,
  deletePlan,
  updatePlan,
  createWorkout,
  getAllWorkouts,
  deleteWorkout,
  updateWorkout,
  createWorkoutSpecifications,
  getAllWorkoutSpecifications,
  updateWorkoutSpecifications,
  createDiet,
  getDiet,
  updateDiet,
  registerTrainee,
  loginTrainee,
  login,
  signup,
};
